<?= $this->render('add-word/sub-file/navigation.phtml') ?>
<div class='main-content'>
<?php
switch($this->url)
{
	case AddWordController::URL_UPLOAD_FILE:
		break;
	case AddWordController::URL_MORE:
		break;
	default: //AddWordController::URL_ADD_INDEX
		echo "<form class='form-inline' name='add_form' id='add_form'>
				  <div class='form-group'>
				    <label class='sr-only' for='english'>English</label>
				    <input type='text' class='form-control' id='english' placeholder='Word (English)'>
				  </div>
				  <div class='form-group'>
				    <label class='sr-only' for='vietnamese'>Vietnamese</label>
				    <input type='text' class='form-control' id='vietnamese' placeholder='Meaning (Vietnamese)'>
				  </div>
				   <div class='form-group'>
				    <label class='sr-only' for='family_type'>Family Type</label>
				    ".
				    	$this->select_html 
				  	."
				  </div>
				  <button type='submit' class='btn btn-default'>Add</button>
				</form>";
		break;
} 
?>
</div>