<div class="container">

  <div class="row">
    <div class="col-sm-3 col-md-12" style="color:red;">
      <?php $this->falseInfo ?>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3 col-md-4" style="background-color:lavender;">
    </div>
    <div class="col-sm-3 col-md-4" style="background-color:lavenderblush; border: 1px solid black;">
  <form role="form" action="index/login" method='post'>
  <div class="form-group">
    <label for="username">Username:</label>
    <input type="text" class="form-control" id="username" name="username">
  </div>

  <div class="form-group">
    <label for="pwd">Password:</label>
    <input type="password" class="form-control" id="pwd" name="pwd">
  </div>
  <div class="checkbox">
    <label><input type="checkbox"> Remember me</label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
  </form>
  </div>

  <div class="col-sm-3 col-md-4" style="background-color:lavender;">
  </div>
</div>
</div>