<?php echo $this->doctype() ?>  
<html>  
<head>  
    <!--<?php echo $this->headTitle() ?>  
    <?php echo $this->headMeta() ?>       
    <?php echo $this->headLink() ?>  
    <?php echo $this->headScript() ?>     -->
    <link rel="stylesheet" type="text/css" href="public/dist/css/bootstrap.css">
    <script src="public/js/jquery-1.11.0.min.js"></script>
    <script src="public/dist/js/bootstrap.min.js"></script>
    <script src="public/js/index1.js"></script>
</head>  
<body> 
    <?php
        echo $this->layout()->content;
    ?>
</body> 
</html>