<!DOCTYPE html>
<?php echo $this->doctype() ?>  
<html>  
<head>  
    <link href="<?php echo $this->baseUrl()?>/public/dist/css/bootstrap.css" rel="stylesheet" type="text/css">
   	<link href="<?php echo $this->baseUrl()?>/public/css/index1.css" rel="stylesheet" type="text/css">
    <?php echo $this->headScript()->appendFile($this->baseUrl() . '/public/js/jquery-1.11.0.min.js');?>
	<?php $this->headScript()->appendFile($this->baseUrl() . '/public/dist/js/bootstrap.min.js');?>
	<script src="<?php echo $this->baseUrl() ?>/public/js/index1.js"></script>
</head>  
<body> 
    <?php
        echo $this->layout()->content;
    ?>
</body> 
</html>